src/adminpannel/urls.py
from django.urls import path
from . import views as ap_view
app_name = 'adminportal'
urlpatterns = [
    path(" ", ap_view.AdminPannel.as_view(), name="adminpannel"),
    path("book/", ap_view.AdminPannelBook.as_view(), name="book"),
    path("user-profile", ap_view.UserPannel.as_view(), name="userpannel"),
    path("exchangerate/<int:pk>", ap_view.UpdateExchangeRate.as_view(), name="exchangerate")
 

]

src/book/urls.py
from django.urls import path
from . import views as b_views
app_name = 'book'
urlpatterns = [
    path('add-book/', b_views.AddBook.as_view(), name='add-book'),
    path('book/<int:pk>', b_views.DetailBook.as_view(), name='detail-book'),
    path('update-book/<int:pk>', b_views.UpdateBook.as_view(), name='update-book'),
    path('delete-book/<int:pk>', b_views.DeleteBook.as_view(), name='delete-book'),
    path('list-book/', b_views.ListBook.as_view(), name='list-book'),
    path('import-list-book/', b_views.book_list_import, name='import-list-book'),
    path('export-list-book/', b_views.book_list_export, name='export-list-book')

]

src/guide/urls.py
from django.urls import path
from . import views as g_views
app_name = 'guide'

urlpatterns = [
    path('add-author/', g_views.AddAuthor.as_view(), name='add-author'),
    path('author/<int:pk>', g_views.DetailAuthor.as_view(), name='detail-author'),
    path('update-author/<int:pk>', g_views.UpdateAuthor.as_view(), name='update-author'),
    path('delete-author/<int:pk>', g_views.DeleteAuthor.as_view(), name='delete-author'),
    path('list-author/', g_views.ListAuthor.as_view(), name='list-author'),

    path('add-genre/', g_views.AddGenre.as_view(), name='add-genre'),
    path('genre/<int:pk>', g_views.DetailGenre.as_view(), name='detail-genre'),
    path('update-genre/<int:pk>', g_views.UpdateGenre.as_view(), name='update-genre'),
    path('delete-genre/<int:pk>', g_views.DeleteGenre.as_view(), name='delete-genre'),
    path('list-genre/', g_views.ListGenre.as_view(), name='list-genre'),

    path('add-series/', g_views.AddSeries.as_view(), name='add-series'),
    path('series/<int:pk>', g_views.DetailSeries.as_view(), name='detail-series'),
    path('update-series/<int:pk>', g_views.UpdateSeries.as_view(), name='update-series'),
    path('delete-series/<int:pk>', g_views.DeleteSeries.as_view(), name='delete-series'),
    path('list-series/', g_views.ListSeries.as_view(), name='list-series'),

    path('add-publishing/', g_views.AddPublishing.as_view(), name='add-publishing'),
    path('publishing/<int:pk>', g_views.DetailPublishing.as_view(), name='detail-publishing'),
    path('update-publishing/<int:pk>', g_views.UpdatePublishing.as_view(), name='update-publishing'),
    path('delete-publishing/<int:pk>', g_views.DeletePublishing.as_view(), name='delete-publishing'),
    path('list-publishing/', g_views.ListPublishing.as_view(), name='list-publishing')
]

src/homepage/urls.py
from django.urls import path
from . import views as hp_view

app_name = 'homepage'

urlpatterns = [
    path("", hp_view.HomePage.as_view(), name='home'),
    path("search/", hp_view.SearchResults.as_view(), name='search')
]

src/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path("cart/", views.cart_view, name='cart'),
    path("delete-position/<int:pk>/", views.DeletePosition.as_view(), name='delete-position'),
    path("make-an-order/", views.MakeAnOrder.as_view(), name='make-an-order'),
    path("success/", views.SuccessView.as_view(), name='success'),
    path("list-order/", views.ListOrder.as_view(), name='list-order'),

    path('detail-order/<int:pk>', views.DetailOrder.as_view(), name='detail-order'),
    path('update-order/<int:pk>', views.UpdateOrder.as_view(), name='update-order'),
    path('delete-order/<int:pk>', views.DeleteOrder.as_view(), name='delete-order'),
    path('staff-update-order/<int:pk>', views.StaffUpdateOrder.as_view(), name='staff-update-order'),
    path("user-list-order/", views.UserListOrder.as_view(), name='user-list-order'),
    path("status-order/<int:pk>", views.UpdateStatusOrder.as_view(), name='status-order')

]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from adminpannel import views as ap_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name = 'adminpannel/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("ref/", include('guide.urls', namespace='guide')),
    path("book/", include('book.urls', namespace='book')),
    path("", include('homepage.urls', namespace='homepage')),
    path("adminportal/", include('adminpannel.urls', namespace='adminportal')),
    path("order/", include('order.urls', namespace='order')),
    path("", include('custom_user.urls', namespace='custom_user')),
    path("comments", include('comments.urls', namespace='comments')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> {% block title %} BOOK SHOP {% endblock title %} </title>


<link href={% static "guide/css/bootstrap.min.css" %} rel="stylesheet">
<link href={% static "icons/bootstrap-icons.css" %} rel="stylesheet">
<link href={% static "guide/css/custom.css" %} rel="stylesheet">



<meta name="theme-color" content="#712cf9">
    <!-- Custom styles for this template -->
  </head>
  <body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'homepage:home'%}"><i class="bi bi-book-half"></i>Главная</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'book:list-book'%}">Книги</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'guide:list-author' %}">Авторы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'guide:list-genre' %}">Жанры</a>
          </li>
          {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'adminportal:adminpannel'%}">Портал администраторов</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/s-admin/">Django admin</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'adminportal:userpannel'%}">Привет,{{user}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login'%}">Войти</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link disabled" >{% now "l d.m.Y" %}</a>
          </li>        </ul>
        <form class="d-flex" role="search" action="{% url 'homepage:search' %}" method="get">
          <input class="form-control me-2" name="tosearch" type="text" placeholder="Поиск..." aria-label="Search">
         <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
       </form>
   <ul class="navbar-nav me-auto mb-2 mb-md-0">
       <li class="nav-item">
        <a class="nav-link" href="{% url 'order:cart'%}"><i class="bi bi-cart"></i>{{total_quantiti_in_cart}}</a>
      </li>
  </ul>
      </div>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
  {% block body %}
   
  {% endblock body %}
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted"> 
    {% block footer %}
        учебный проект. 2022. IT academy
    {% endblock footer %} 
    </span>
  </div>
</footer>
    <script src={% static "guide/js/bootstrap.bundle.min.js" %} ></script>
    <script src={% static "guide/js/bootstrap.min.js" %} ></script>
  </body>
</html>