src/adminpannel/urls.py
from django.urls import path
from . import views as ap_view
app_name = 'adminportal'
urlpatterns = [
    path(" ", ap_view.AdminPannel.as_view(), name="adminpannel"),
    path("book/", ap_view.AdminPannelBook.as_view(), name="book"),
    path("user-profile", ap_view.UserPannel.as_view(), name="userpannel"),
    path("exchangerate/<int:pk>", ap_view.UpdateExchangeRate.as_view(), name="exchangerate")
 

]

src/book/urls.py
from django.urls import path
from . import views as b_views
app_name = 'book'
urlpatterns = [
    path('add-book/', b_views.AddBook.as_view(), name='add-book'),
    path('book/<int:pk>', b_views.DetailBook.as_view(), name='detail-book'),
    path('update-book/<int:pk>', b_views.UpdateBook.as_view(), name='update-book'),
    path('delete-book/<int:pk>', b_views.DeleteBook.as_view(), name='delete-book'),
    path('list-book/', b_views.ListBook.as_view(), name='list-book'),
    path('import-list-book/', b_views.book_list_import, name='import-list-book'),
    path('export-list-book/', b_views.book_list_export, name='export-list-book')

]

src/custom_user/urls.py
from django.urls import path
from . import views

app_name = 'custom_user'

urlpatterns = [
    path("registration/", views.RegisterUser.as_view(), name='registration'),
    path("create-user/", views.CreateUser.as_view(), name='create-user'),
    path('list-user/', views.ListExtendUser.as_view(), name='list-user'),
    path("detail-user/<int:pk>", views.DetailUser.as_view(), name='detail-user'),
    path("delete-user/<int:pk>/", views.DeleteUser.as_view(), name='delete-user'),
    path('update-user/<int:pk>', views.UpdateUser.as_view(), name='update-user'),
    path('update-extenduser/<int:pk>', views.UpdateExtendUser.as_view(), name='update-extenduser'),

]

src/guide/urls.py
from django.urls import path
from . import views as g_views
app_name = 'guide'

urlpatterns = [
    path('add-author/', g_views.AddAuthor.as_view(), name='add-author'),
    path('author/<int:pk>', g_views.DetailAuthor.as_view(), name='detail-author'),
    path('update-author/<int:pk>', g_views.UpdateAuthor.as_view(), name='update-author'),
    path('delete-author/<int:pk>', g_views.DeleteAuthor.as_view(), name='delete-author'),
    path('list-author/', g_views.ListAuthor.as_view(), name='list-author'),

    path('add-genre/', g_views.AddGenre.as_view(), name='add-genre'),
    path('genre/<int:pk>', g_views.DetailGenre.as_view(), name='detail-genre'),
    path('update-genre/<int:pk>', g_views.UpdateGenre.as_view(), name='update-genre'),
    path('delete-genre/<int:pk>', g_views.DeleteGenre.as_view(), name='delete-genre'),
    path('list-genre/', g_views.ListGenre.as_view(), name='list-genre'),

    path('add-series/', g_views.AddSeries.as_view(), name='add-series'),
    path('series/<int:pk>', g_views.DetailSeries.as_view(), name='detail-series'),
    path('update-series/<int:pk>', g_views.UpdateSeries.as_view(), name='update-series'),
    path('delete-series/<int:pk>', g_views.DeleteSeries.as_view(), name='delete-series'),
    path('list-series/', g_views.ListSeries.as_view(), name='list-series'),

    path('add-publishing/', g_views.AddPublishing.as_view(), name='add-publishing'),
    path('publishing/<int:pk>', g_views.DetailPublishing.as_view(), name='detail-publishing'),
    path('update-publishing/<int:pk>', g_views.UpdatePublishing.as_view(), name='update-publishing'),
    path('delete-publishing/<int:pk>', g_views.DeletePublishing.as_view(), name='delete-publishing'),
    path('list-publishing/', g_views.ListPublishing.as_view(), name='list-publishing')
]

src/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path("cart/", views.cart_view, name='cart'),
    path("delete-position/<int:pk>/", views.DeletePosition.as_view(), name='delete-position'),
    path("make-an-order/", views.MakeAnOrder.as_view(), name='make-an-order'),
    path("success/", views.SuccessView.as_view(), name='success'),
    path("list-order/", views.ListOrder.as_view(), name='list-order'),

    path('detail-order/<int:pk>', views.DetailOrder.as_view(), name='detail-order'),
    path('update-order/<int:pk>', views.UpdateOrder.as_view(), name='update-order'),
    path('delete-order/<int:pk>', views.DeleteOrder.as_view(), name='delete-order'),
    path('staff-update-order/<int:pk>', views.StaffUpdateOrder.as_view(), name='staff-update-order'),
    path("user-list-order/", views.UserListOrder.as_view(), name='user-list-order'),
    path("status-order/<int:pk>", views.UpdateStatusOrder.as_view(), name='status-order')

]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from adminpannel import views as ap_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name = 'adminpannel/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("ref/", include('guide.urls', namespace='guide')),
    path("book/", include('book.urls', namespace='book')),
    path("", include('homepage.urls', namespace='homepage')),
    path("adminportal/", include('adminpannel.urls', namespace='adminportal')),
    path("order/", include('order.urls', namespace='order')),
    path("", include('custom_user.urls', namespace='custom_user')),
    path("comments", include('comments.urls', namespace='comments')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/adminpannel/models.py
from django.db import models

class ExchangeRate(models.Model):
    rate = models.DecimalField(
        verbose_name='Курс',
        max_digits=5,
        decimal_places=2
    )

    last_change = models.DateField(
        verbose_name='Дата последнего изменение карточки',
        auto_now=True
    )

src/book/models.py
from django.db import models
from django.urls import reverse_lazy


class Book(models.Model):
    """модель книги"""
    ZERO = '0'
    ONE = '1'
    TWO = '2'
    THREE = '3'
    FOUR = '4'
    FIVE = '5'
    SIX = '6'
    SEVEN = '7'
    EIGHT = '8'
    NINE = '9'
    TEN = '10'

    CHOISE_GROUP = {
        (ZERO, '0'),
        (ONE, '1'),
        (TWO, '2'),
        (THREE, '3'),
        (FOUR, '4'),
        (FIVE, '5'),
        (SIX, '6'),
        (SEVEN, '7'),
        (EIGHT, '8'),
        (NINE, '9'),
        (TEN, '10')
    }

    cover = models.ImageField(
        verbose_name='Обложка книги',
        upload_to='uploads/%Y/%m/%d'

    )

    name = models.CharField(
        verbose_name='Название',
        max_length=40
    )

    author_book = models.ManyToManyField(
        'guide.Author',
        verbose_name='Автор',
        related_name='authorbook',
    )

    series_book = models.ForeignKey(
        'guide.Series',
        verbose_name='Серия',
        on_delete=models.PROTECT,
        related_name='seriesbook'
    )

    genre_book = models.ForeignKey(
        'guide.Genre',
        verbose_name='Жанр',
        on_delete=models.PROTECT,
        related_name='genrebook'
    )
    publishing_book = models.ForeignKey(
        'guide.Publishing',
        verbose_name='Издательство',
        on_delete=models.PROTECT,
        related_name='publishingbook'
    )

    price = models.DecimalField(
        verbose_name='Цена',
        max_digits=5,
        decimal_places=2
    )
    last_change = models.DateField(
        verbose_name='Дата последнего изменение карточки',
        auto_now=True
    )
    add_to_catalog = models.DateField(
        verbose_name='Дата добавления в каталог',
        auto_now_add=True
    )

    quantity_available = models.PositiveSmallIntegerField(
        verbose_name='Количество в наличии'
    )

    weight = models.PositiveSmallIntegerField(
        verbose_name='Вес(гр.)',
        blank=True,
        null=True
    )
    quantity_of_pages = models.PositiveSmallIntegerField(
        verbose_name='Количество страниц',
        blank=True,
        null=True
    )

    binding = models.TextField(
        verbose_name='Переплет',
        max_length=100,
        blank=True,
        null=True
    )

    book_format = models.TextField(
        verbose_name='Формат',
        max_length=100,
        blank=True,
        null=True
    )

    year_of_publication = models.DecimalField(
        verbose_name='Год издания',
        max_digits=4,
        decimal_places=0,
        blank=True,
        null=True
    )

    isbn = models.TextField(
        verbose_name='ISBN',
        max_length=100,
        blank=True,
        null=True
    )

    age_restrictions = models.TextField(
        verbose_name='Возрастные ограничения',
        max_length=10,
        blank=True,
        null=True
    )

    rating = models.CharField(
        verbose_name='Рейтинг',
        max_length=50,
        choices=CHOISE_GROUP,
        default=ZERO

    )

    availability = models.BooleanField(
        verbose_name='Доступен для заказа'
    )

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse_lazy('book:detail-book', kwargs={'pk': self.pk})

src/adminpannel/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class ExchangeRateForm(forms.ModelForm):
    class Meta:
        model = models.ExchangeRate
        fields = ('rate',)

src/book/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class BookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'

src/adminpannel/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from book import models, forms
from django.contrib.auth.models import User
from . import models as a_models
from . import forms as a_forms


class AdminPannel(PermissionRequiredMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'adminpannel/adminpannel.html'
    permission_required = ('book.change_book', 'auth.change_user')
    login_url = reverse_lazy('login')


class AdminPannelBook(PermissionRequiredMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'adminpannel/book.html'
    permission_required = ('book.change_book', 'auth.change_user')
    login_url = reverse_lazy('login')


class UserPannel(LoginRequiredMixin, generic.TemplateView):
    template_name = 'adminpannel/users.html'
    login_url = reverse_lazy('login')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        u_id = self.request.user
        user_pk = User.objects.get(pk=u_id.pk)
        context['pk'] = user_pk.pk
        return context


class UpdateExchangeRate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = a_models.ExchangeRate
    form_class = a_forms.ExchangeRateForm
    permission_required = 'book.add_book'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('adminportal:adminpannel')
    template_name = 'adminpannel/edit_exchange_rate.html'

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['operation'] = 'Редактировать данные о книге'
    #     return context

src/book/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from comments import models as c_models
from comments import forms as c_forms
from django.views.generic.edit import FormMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
from tablib import Dataset

from .resources import BookResource

from . import models, forms


# кинги:

class AddBook(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = models.Book
    form_class = forms.BookForm
    permission_required = 'book.add_book'
    login_url = reverse_lazy('login')
    template_name = 'book/edit_book.html'
    success_url = reverse_lazy('book:list-book')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Добавить книгу'
        return context


class DetailBook(FormMixin, generic.DetailView):
    model = models.Book
    template_name = 'book/detail_book.html'
    form_class = c_forms.CommentToBookForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        return self.form_valid(form)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.book = self.get_object()
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('book:detail-book', kwargs={'pk': self.get_object().pk})


class UpdateBook(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Book
    form_class = forms.BookForm
    permission_required = 'book.add_book'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('book:list-book')
    template_name = 'book/edit_book.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Редактировать данные о книге'
        return context


class DeleteBook(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Book
    permission_required = 'book.delete_book'
    login_url = reverse_lazy('login')
    template_name = 'book/delete_book.html'
    success_url = reverse_lazy('book:list-book')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Удалить книгу'
        context['alarm_message'] = 'Вы точно хотите удалить данную книгу?'
        return context


class ListBook(generic.ListView):
    model = models.Book
    template_name = 'book/list_book.html'


# импорт/экспорт списков книг

def book_list_export(request):
    if request.user.is_authenticated == request.user.is_staff:
        if request.method == 'POST':
            file_format = request.POST['file-format']
            book_resource = BookResource()
            dataset = book_resource.export()
            if file_format == 'CSV':
                response = HttpResponse(dataset.csv, content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename="exported_data.csv"'
                return response
            elif file_format == 'JSON':
                response = HttpResponse(dataset.json, content_type='application/json')
                response['Content-Disposition'] = 'attachment; filename="exported_data.json"'
                return response
            elif file_format == 'XLS (Excel)':
                response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
                response['Content-Disposition'] = 'attachment; filename="exported_data.xls"'
                return response

        return render(request, 'book/export_book.html')
    else:
        raise PermissionDenied()


def book_list_import(request):
    if request.user.is_authenticated == request.user.is_staff:
        if request.method == 'POST':
            file_format = request.POST['file-format']
            book_resource = BookResource()
            dataset = Dataset()
            new_book = request.FILES['importData']

            if file_format == 'CSV':
                imported_data = dataset.load(new_book.read().decode('utf-8'), format='csv')
                result = book_resource.import_data(dataset, dry_run=True)
            elif file_format == 'JSON':
                imported_data = dataset.load(new_book.read().decode('utf-8'), format='json')
                result = book_resource.import_data(dataset, dry_run=True)

            if not result.has_errors():
                book_resource.import_data(dataset, dry_run=False)

        return render(request, 'book/import_book.html')
    else:
        raise PermissionDenied()

src/adminpannel/templates/adminpannel/adminpannel.html
{% extends 'base.html' %}


{% block title %}
Портал администраторов
{% endblock title %}

{% block body %}
{% comment %} {% csrf_token %} {% endcomment %}
<p align="right">
    login пользователя: {{user}} <br>
    id пользователя: {{user.pk}}<br> 
    Имя: {{user.first_name|default:'не указано'}}<br>
    Фамилия: {{user.last_name|default:'не указано'}} <br>
    email: {{ user.email|default:'не указан' }}<br>
</p>
<h1 align="right">
<p  class="btn btn-warning"> <a href= "{% url 'adminportal:book' %}" > Книги, справочники </a></p><br>
<p  class="btn btn-warning"> <a href= "{% url 'custom_user:list-user' %}"> Пользователи </a></p><br>
<p  class="btn btn-warning"> <a href= "{% url 'order:list-order' %}"> Заказы </a></p><br>
<p  class="btn btn-warning"> <a href= "{% url 'book:export-list-book' %}"> Выгрузить список книг из формата СSV </a></p><br>
<p  class="btn btn-warning"> <a href= "{% url 'book:import-list-book' %}"> Загрузить список книг из формата СSV </a></p><br>
<p  class="btn btn-warning"> <a href= "{% url 'adminportal:exchangerate' pk=1 %}"> Изменить курс валюты </a></p><br>
</h1>
{% endblock body %}

src/adminpannel/templates/adminpannel/book.html
{% extends 'base.html' %}


{% block title %}
Редактирование
{% endblock title %}

{% block body %}
{% csrf_token %}
    <h1>!</h1>
    <table class="table table-bordered border-primary">

      <tr>
        <td>Редактирование </td>
        <td> Добавление </td>
      </tr>    
    <tr>
      <td><a href= "{% url 'book:list-book' %}"> Книги </a> </td>
      <td><a href= "{% url 'book:add-book' %}"> Добавить кингу </a> </td>
    </tr> 

    <tr>
      <td><a href= "{% url 'guide:list-author' %}"> Авторы </a> </td>
      <td><a href= "{% url 'guide:add-author' %}"> Добавить автора </a> </td>
    </tr> 
    <tr>
      <td><a href= "{% url 'guide:list-series' %}"> Серии книг </a> </td>
      <td><a href= "{% url 'guide:add-series' %}"> Добавить серию </a> </td>
    </tr> 
    <tr>
      <td><a href= "{% url 'guide:list-genre' %}"> Жанры </a> </td>
      <td><a href= "{% url 'guide:add-genre' %}"> Добавить жанр </a> </td>
    </tr> 
    <tr>
      <td><a href= "{% url 'guide:list-publishing' %}"> Издательства </a> </td>
      <td><a href= "{% url 'guide:add-publishing' %}"> Добавить издательство </a> </td>
    </tr>

  </table>
{% endblock body %}

src/adminpannel/templates/adminpannel/edit_exchange_rate.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Изменить курс валюты
{% endblock title %}

{% block body %}
    <h1>Изменить курс валюты</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form |crispy}}
        <input type="submit" class="btn btn-success" value="Ok">
        </form>
{% endblock body %}

src/adminpannel/templates/adminpannel/login.html
{% extends "base.html" %}

{% block body %}

{% if form.errors %}
<p>Имя пользователя или пароль не совпадают. Повторите попытку.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>У Вас нет доступа к данной станице. Чтобы продолжить,
        пожалуйста, войдите в систему с учетной записью, имеющей доступ.</p>
    {% else %}
    <p>Войдите в систему, чтобы увидеть эту страницу.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<br><tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
<br><input type="submit" value="Войти">
<input type="hidden" name="next" value="{{ next }}">
</form>
<br>
<p  class="btn btn-warning"> <a href= "{% url 'custom_user:registration' %}" > Зарегистрироваться </a></p><br>
{# Assumes you set up the password_reset view in your URLconf #}
{% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}


  {% endblock body %}

src/adminpannel/templates/adminpannel/login_origin.html
{% extends "base.html" %}

{% block body %}

{% if form.errors %}
<p>Имя пользователя или пароль не совпадают. Повторите попытку.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>У Вас нет доступа к данной станице. Чтобы продолжить,
        пожалуйста, войдите в систему с учетной записью, имеющей доступ.</p>
    {% else %}
    <p>Войдите в систему, чтобы увидеть эту страницу.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Войти">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
{% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}

{% endblock body %}

src/adminpannel/templates/adminpannel/users.html
{% extends 'base.html' %}
{% block title %}
Портал администраторов
{% endblock title %}

{% block body %}

<p align="left">
    login пользователя: {{user}} <br>
    id пользователя: {{user.pk}}<br> 
    {% if user.is_staff %}
    Статус: персонал<br>
    {% else %}
    Статус: клиент<br>
    {% endif %}
  
    Имя: {{user.first_name|default:'не указано'}}<br>
    Фамилия: {{user.last_name|default:'не указано'}} <br>
    email: {{ user.email|default:'не указан' }}<br>
</p>
<h1 align="left">
  {% if user.is_staff  %}
  <p  class="btn btn-warning"> <a href= "{% url 'adminportal:adminpannel' %}" > Портал администраторов </a></p><br>
  {% endif %}


{% if user.extenduser.pk %}
<p  class="btn btn-warning"> <a href= "{% url 'custom_user:detail-user' pk=pk %}" > Информация о профиле/Редактировать  </a></p><br>
{% else %}
<p  class="btn btn-warning"> <a href= "{% url 'custom_user:create-user'  %}" > Добавьте расширенные данные  </a></p><br>
{% endif %}



<p  class="btn btn-warning"> <a href= "{% url 'order:user-list-order' %}"> Мои заказы </a></p><br>
{% comment %} 
<p  class="btn btn-warning"> <a href= "{% url 'order:list-order' %}"> Заказы </a></p><br>
<p  class="btn btn-warning"> <a href= "{% url 'book:list-book' %}"> Загрузить список книг из формата СSV </a></p><br>
<p  class="btn btn-warning"> <a href= "{% url 'book:list-book' %}"> ?! </a></p><br> {% endcomment %}
</h1>
{% endblock body %}