src/book/urls.py
from django.urls import path
from . import views as b_views
app_name = 'book'
urlpatterns = [
    path('add-book/', b_views.AddBook.as_view(), name='add-book'),
    path('book/<int:pk>', b_views.DetailBook.as_view(), name='detail-book'),
    path('update-book/<int:pk>', b_views.UpdateBook.as_view(), name='update-book'),
    path('delete-book/<int:pk>', b_views.DeleteBook.as_view(), name='delete-book'),
    path('list-book/', b_views.ListBook.as_view(), name='list-book'),
    path('import-list-book/', b_views.book_list_import, name='import-list-book'),
    path('export-list-book/', b_views.book_list_export, name='export-list-book')

]

src/comments/urls.py
from django.urls import path
from . import views 
app_name = 'comments'
urlpatterns = [
    path('delete-comment-book/<int:pk>', views.DeleteCommentBook.as_view(), name='delete-comment-book'),
    path('delete-comment-order/<int:pk>', views.DeleteCommentOrder.as_view(), name='delete-comment-order')
]

src/homepage/urls.py
from django.urls import path
from . import views as hp_view

app_name = 'homepage'

urlpatterns = [
    path("", hp_view.HomePage.as_view(), name='home'),
    path("search/", hp_view.SearchResults.as_view(), name='search')
]

src/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path("cart/", views.cart_view, name='cart'),
    path("delete-position/<int:pk>/", views.DeletePosition.as_view(), name='delete-position'),
    path("make-an-order/", views.MakeAnOrder.as_view(), name='make-an-order'),
    path("success/", views.SuccessView.as_view(), name='success'),
    path("list-order/", views.ListOrder.as_view(), name='list-order'),

    path('detail-order/<int:pk>', views.DetailOrder.as_view(), name='detail-order'),
    path('update-order/<int:pk>', views.UpdateOrder.as_view(), name='update-order'),
    path('delete-order/<int:pk>', views.DeleteOrder.as_view(), name='delete-order'),
    path('staff-update-order/<int:pk>', views.StaffUpdateOrder.as_view(), name='staff-update-order'),
    path("user-list-order/", views.UserListOrder.as_view(), name='user-list-order'),
    path("status-order/<int:pk>", views.UpdateStatusOrder.as_view(), name='status-order')

]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from adminpannel import views as ap_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name = 'adminpannel/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("ref/", include('guide.urls', namespace='guide')),
    path("book/", include('book.urls', namespace='book')),
    path("", include('homepage.urls', namespace='homepage')),
    path("adminportal/", include('adminpannel.urls', namespace='adminportal')),
    path("order/", include('order.urls', namespace='order')),
    path("", include('custom_user.urls', namespace='custom_user')),
    path("comments", include('comments.urls', namespace='comments')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/order/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name='Корзина пользователя',
        related_name='user_cart',
        null=True,
        blank=True
    )

    def total_price(self):
        all_books_positions = self.cart.all()
        total_price = 0
        for book_position in all_books_positions:
            total_price += book_position.price_per_position
        return total_price


class BookInCart(models.Model):
    book = models.ForeignKey(
        'book.Book',
        verbose_name='книга в корзине',
        related_name='book_in_cart',
        on_delete=models.PROTECT
    )
    cart = models.ForeignKey(
        'order.Cart',
        verbose_name='корзина',
        related_name='cart',
        on_delete=models.PROTECT
    )
    quantity = models.IntegerField(
        verbose_name='количество',
        default=1
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=5,
        decimal_places=2
    )
    created_date = models.DateTimeField(
        verbose_name='дата создания',
        auto_now_add=True
    )
    update_date = models.DateTimeField(
        verbose_name='дата изменения',
        auto_now=True
    )

    @property
    def price_per_position(self):
        return self.price * self.quantity

    def __str__(self):
        return str(self.book)


class Statuses(models.Model):
    status = models.CharField(
        verbose_name='статус',
        max_length=40
    )

    def __str__(self):
        return self.status


class Order(models.Model):
    cart = models.OneToOneField(
        'order.Cart',
        verbose_name='корзина',
        related_name='order',
        on_delete=models.PROTECT
    )

    status = models.ForeignKey(
        'order.Statuses',
        verbose_name='статус заказа',
        related_name='statuses',
        on_delete=models.PROTECT,

    )
    name = models.CharField(
        verbose_name='ФИО',
        max_length=200
    )

    telefon_number = models.PositiveIntegerField(
        verbose_name='номер телефона'
    )
    email_adress = models.EmailField(
        verbose_name='email',
        max_length=254)

    adress = models.TextField(
        verbose_name='Адрес',
        max_length=200
    )

    created_date = models.DateTimeField(
        verbose_name='дата создания',
        auto_now_add=True
    )
    updated_date = models.DateTimeField(
        verbose_name='дата изменения',
        auto_now=True
    )

    additional_information = models.TextField(
        verbose_name='Дополнительная информация',
        max_length=500,
        blank=True,
        null=True
    )

    def __str__(self):
        return str(self.pk)

src/order/forms.py
from django import forms
from . import models


class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ('name', 'telefon_number', 'email_adress', 'adress', 'additional_information')


class StaffOrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ('status', 'name', 'telefon_number', 'email_adress', 'adress', 'additional_information')


class ChangeOrderStatusForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ChangeOrderStatusForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['status'].queryset = models.Statuses.objects.filter(status='Отменен')

    class Meta:
        model = models.Order
        fields = ('status',)

src/order/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from . import models, forms
from book import models as b_models
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.contrib.auth.models import User
from django.views.generic.edit import FormMixin
from comments import forms as c_forms
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Q


def cart_view(request):
    context = {}
    context['cart'] = None
    if request.method == 'POST':
        book_pk = request.POST.get('book_pk')
        quantity = request.POST.get('quantity')

        if book_pk and quantity:
            cart_id = int(request.session.get('cart_id', 0))
            if cart_id == 0:
                cart_id = None
            if request.user.is_authenticated:
                user = request.user
                # print(user)
            else:
                user = None
            cart, created = models.Cart.objects.get_or_create(
                pk=cart_id,
                defaults={'user': user}
            )
            context['cart'] = cart
            if created:
                request.session['cart_id'] = cart.pk

            book = b_models.Book.objects.get(pk=int(book_pk))
            price = book.price

            book_in_cart, created = models.BookInCart.objects.get_or_create(
                book=book,
                cart=cart,
                defaults={
                    'quantity': quantity,
                    'price': price
                }
            )
            if not created:
                book_in_cart.quantity += int(quantity)
                book_in_cart.save()
    else:
        cart_id = request.session.get('cart_id')
        if cart_id:
            cart = models.Cart.objects.get(pk=cart_id)
            context['cart'] = cart

    return render(
        request=request,
        template_name='order/cart.html',
        context=context

    )


class DeletePosition(UserPassesTestMixin, generic.DeleteView):
    model = models.BookInCart
    success_url = reverse_lazy('order:cart')
    template_name = 'order/delete_position.html'

    def test_func(self):
        if self.request.user.is_authenticated != self.request.user.is_staff:
            detail = self.get_object()
            if self.request.user == detail.cart.user:
                return True
            return False
        else:
            return True


class MakeAnOrder(generic.CreateView):
    model = models.Order
    template_name = 'order/create_order.html'
    form_class = forms.OrderForm
    success_url = reverse_lazy('order:success')

    def form_valid(self, form):
        cart = models.Cart.objects.get(pk=self.request.session.get('cart_id'))
        form.instance.cart = cart
        form.instance.status = models.Statuses.objects.get(pk=1)
        return super().form_valid(form)

    def get_success_url(self):
        del self.request.session['cart_id']
        # subject = 'Новый заказ'
        # message = 'Появился новый заказ!'
        # email_from = 'fortestsendingdjango@mail.ru'
        # recipient_list = ['someone736970@gmail.com', ]
        # send_mail( subject, message, email_from, recipient_list )
        return super().get_success_url()


class SuccessView(generic.TemplateView):
    model = models.Order
    template_name = 'order/success_order.html'
    print(model.name)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # print(models.Order.objects.get(self.request.session.get(pk=10)))
        # context['order'] = models.Order.objects.get()
        # last_order = models.Order.objects.all().order_by('-id')[:1]
        # print(last_order.name )
        # context['order'] = last_order
        return context


class ListOrder(PermissionRequiredMixin, LoginRequiredMixin, generic.ListView):
    model = models.Order
    permission_required = ('book.change_book', 'auth.change_user')
    template_name = 'order/list_order.html'
    login_url = reverse_lazy('login')

    def get_queryset(self):
        return super(ListOrder, self).get_queryset().order_by('-updated_date')


class UserListOrder(LoginRequiredMixin, generic.ListView):
    model = models.Cart
    template_name = 'order/user_list_order.html'
    login_url = reverse_lazy('login')

    def get_queryset(self):
        user_1 = self.request.user
        mod = models.Cart.objects.all()
        user_2 = self.request.user.user_cart.all()
        print('!!!!!!!!!!!!!!!!!', user_1, mod, user_2)
        object_list = models.Cart.objects.filter(user=user_1)
        return object_list


class DetailOrder(FormMixin, UserPassesTestMixin, LoginRequiredMixin, generic.DetailView):
    model = models.Order
    template_name = 'order/detail_order.html'
    login_url = reverse_lazy('login')
    form_class = c_forms.CommentToOrderForm

    def test_func(self):
        if self.request.user.is_authenticated != self.request.user.is_staff:
            detail = self.get_object()
            if self.request.user == detail.cart.user:
                return True
            return False
        else:
            return True

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        return self.form_valid(form)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.order = self.get_object()
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('order:detail-order', kwargs={'pk': self.get_object().pk})


class UpdateOrder(UserPassesTestMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.Order
    form_class = forms.OrderForm
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('homepage:home')
    template_name = 'order/edit_order.html'

    def test_func(self):
        if self.request.user.is_authenticated != self.request.user.is_staff:
            detail = self.get_object()
            if self.request.user == detail.cart.user:
                return True
            return False
        else:
            return True


class DeleteOrder(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Order
    permission_required = 'book.delete_book'
    login_url = reverse_lazy('login')
    template_name = 'order/delete_order.html'
    success_url = reverse_lazy('order:list-order')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Удалить заказ'
        context['alarm_message'] = 'Вы точно хотите удалить данный заказ?'
        return context


class StaffUpdateOrder(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Order
    form_class = forms.StaffOrderForm
    permission_required = 'book.add_book'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('order:list-order')
    template_name = 'order/staff_edit_order.html'


class UpdateStatusOrder(UserPassesTestMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.Order
    form_class = forms.ChangeOrderStatusForm
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('adminportal:userpannel')
    template_name = 'order/status_order.html'

    def test_func(self):
        if self.request.user.is_authenticated != self.request.user.is_staff:
            detail = self.get_object()
            if self.request.user == detail.cart.user:
                return True
            return False
        else:
            return True

src/order/templates/order/cart.html
{% extends 'base.html' %}


{% block title %}
Корзина
{% endblock title %}

{% block body %}

Корзина

{% endblock body %}

src/order/templates/order/create_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Oформление заказа
{% endblock title %}

{% block body %}

<h1>Оформление заказа</h1>
{% comment %} <table class = 'table'>
<tr>
    <td>Название</td>
    <td>Количество</td>
    <td>Цена за книгу</td>
    <td>Цена за позицию</td>
    <td>Удалить</td>
</tr>    
{% for book_cart in cart.cart.all  %}
<tr>   
  <td>{{book_cart.book}}</td>
  <td>{{book_cart.quantity}}</td>
  <td>{{book_cart.price}}</td>
  <td>{{book_cart.price_per_position}}</td>
  <td>
    <a href="{% url 'order:delete-position' book_cart.pk %}" class="btn btn-danger">Удалить</a>
  </td> 
</tr>
{% endfor %}
<tr>
    <td>Итого</td>
    <td colspan="2"></td>
    <td>{{cart.total_price}}</td>
    <td></td>
</tr>  {% endcomment %}
<form action="{% url 'order:make-an-order' %}" method="post">
  {% csrf_token %}
  {{form |crispy}}
  <button type="submit" class="btn btn-success">Заказать</button>
</form>


{% endblock body %}

src/order/templates/order/delete_order.html
{% extends 'base.html' %}


{% block title %}
{{operation}}
{% endblock title %}

{% block body %}
    <h1>{{operation}}</h1>
    <h2>{{alarm_message}}</h2>
    ID заказа: {{object.pk}}<br>
    № корзины: {{object.cart}}<br>
    Статус: {{object.status}}<br>
    Имя покупателя: {{object.name}}<br>
    Номер телефона: {{object.telefon_number}}<br>
    Адрес доставки: {{object.adress}}<br>
    email: {{object.email_adress}}<br>
    Дата оформления заказа: {{object.created_date}}<br>
    Дата последнего изменения заказа: {{object.updated_date}}<br>
    Дополнительная информация: {{object.additional_information}}<br>
         
    <form method = 'post'>
        {%csrf_token%}           
        <button type="submit" class="btn btn-danger">ДА</button>
    </form>
{% endblock body %}

src/order/templates/order/delete_position.html
{% extends 'base.html' %}


{% block title %}
Удаление товара из корзины
{% endblock title %}


{% block body %}

    <h1>Удаление товара из корзины</h1>
    <h2>Вы действительно хотите удалить данную книгу из корзины?</h2>
    {{object.book}}<br>
    {{object.quantity}}<br>
    {{object.price}}<br>
    {{object.price_per_position}}<br> 
    <form method = 'post'>
        {%csrf_token%}           
        <button type="submit" class="btn btn-danger">ДА</button>
    </form>
{% endblock body %}

src/order/templates/order/detail_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Информация о заказе
{% endblock title %}

{% block body %}
{% csrf_token %}
    <h1>Информация о заказе</h1>
   
   <div>
   ID заказа: {{object.pk}}<br>
   № корзины: {{object.cart.pk}}<br>
   заказчик: {{object.cart.user}}<br>
   Статус: {{object.status}}<br>
   Имя покупателя: {{object.name}}<br>
   Номер телефона: {{object.telefon_number}}<br>
   Адрес доставки: {{object.adress}}<br>
   email: {{object.email_adress}}<br>
   Дата оформления заказа: {{object.created_date}}<br>
   Дата последнего изменения заказа: {{object.updated_date}}<br>
   Дополнительная информация: {{object.additional_information}}<br>
</div>
<div>
  <h3>Товары в заказе</h3>
<table class="table table-bordered border-primary">
<tr>
  {% if user.is_staff %}
  <td> pk book in cart</td>
  {% endif %}

  <td> Название </td>
  <td> Количечство </td>
  <td> Цена за единицу </td>
  <td> Цена за позицию </td>
  {% if user.is_staff %}

  <td> Удалить </td>
  {% endif %}
</tr>
{% for book in object.cart.cart.all %}
<tr>
  {% if user.is_staff %}
  <td>{{book.pk}}</td>
  {% endif %}
  <td> {{book}} </td>
  <td> {{book.quantity}} </td>
  <td> {{book.price}} </td>
  <td> {{book.price_per_position}} </td>
  {% if user.is_staff %}
  <td> <a href= "{% url 'order:delete-position' pk=book.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить</a> </td>
  
  {% endif %}
</tr>
{% endfor %}
</table>
<p>Общая сумма заказа :{{object.cart.total_price}} </p>
{% if user.is_staff %}
<h3><a href= "{% url 'order:staff-update-order' pk=object.pk %}" class="btn btn-success"> Редактировать статус заказа/контактые данные заказчика  </a> | <a href= "{% url 'order:status-order' pk=object.pk %}" class="btn btn-danger"> Изменить статус заказа</a></h3>
{% else %}
 <h3><a href= "{% url 'order:update-order' pk=object.pk %}" class="btn btn-success"> Редактировать контактые данные  </a>  | <a href= "{% url 'order:status-order' pk=object.pk %}" class="btn btn-danger"> Отменить заказ</a> </h3> 
{% endif %}

{% if object.order_comment.all.count == 0  %}
    <p>Комментариев нет<br>
    </p>
    {% else %}
    <p>Комментарии к заказу({{object.order_comment.all.count}}):</p>
    <ul>
    {% for comment in object.order_comment.all %}
    <li>
        {% if user.is_staff %}
        pk комментария: {{comment.pk}}
        {% endif %}
        автор:{{comment.author}} <br>
        {{comment.create_date}} <br>
        сообщение:{{comment.message}} <br>
        <br>
        
        {% if user.is_authenticated != user.is_staff %}
        {% if user == comment.author %}
         проверка1 <a href= "{% url 'comments:delete-comment-order' pk=comment.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить комментарий</a><br><br>
        {% endif %}
        {% else %}
        проверка2 <a href= "{% url 'comments:delete-comment-order' pk=comment.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить комментарий</a><br><br>
        {% endif %}
         
    </li>
    {% endfor %}
    </ul>
    {% endif %}
    <p>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form |crispy}}
        <input type="submit" class="btn btn-success" value="Ok">
        </form>
    </p>
</div>


{% endblock body %}

src/order/templates/order/edit_order.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Редактировать данные заказа
{% endblock title %}

{% block body %}
    <h1>Редактировать данные заказа</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form |crispy}}
        <input type="submit" class="btn btn-success" value="Ok">
        </form>
{% endblock body %}

src/order/templates/order/list_order.html
{% extends 'base.html' %}


{% block title %}
Заказы
{% endblock title %}

{% block body %}


    <h1>Список Заказов</h1>
    <table class="table table-bordered border-primary">
    {% if user.is_staff %}
      <tr>
        <td>Изменить данные </td>
        <td> Данные заказа </td>
        <td> Статус </td>
        <td> Покупатель </td>
        <td>Login покупателя</td>
        <td> дата создания </td>
        <td> Дата редактирования </td>
        <td> Удаление </td>
      </tr>
    {% for obj in object_list %}


      <tr>

        <td><a href= "{% url 'order:update-order' pk=obj.pk %}"> {{obj.pk}} </a> </td>  
        <td><a href= "{% url 'order:detail-order' pk=obj.pk %}">{{obj.cart}} </a></td> 
        <td><a href= "{% url 'order:staff-update-order' pk=obj.pk %}" class="btn btn-success"> {{obj.status}} </a></td>
        <td> {{obj.name}} </td>
        <td> {{obj.cart.user}} </td>
        <td>{{obj.created_date}} </td>
        <td>{{obj.updated_date}}</td>
        <td><a href= "{% url 'order:delete-order' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить</a></td> 
      </tr> 

    {% endfor %}
    {% endif %}
    </table>        
    {% endblock body %}

src/order/templates/order/staff_edit_order.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
редактироваить данные заказа
{% endblock title %}

{% block body %}
<div>
    ID заказа: {{object.pk}}<br>
    № корзины: {{object.cart.pk}}<br>
    заказчик: {{object.cart.user}}<br>
    Статус: {{object.status}}<br>
    Имя покупателя: {{object.name}}<br>
    Номер телефона: {{object.telefon_number}}<br>
    Адрес доставки: {{object.adress}}<br>
    email: {{object.email_adress}}<br>
    Дата оформления заказа: {{object.created_date}}<br>
    Дата последнего изменения заказа: {{object.updated_date}}<br>
    Дополнительная информация: {{object.additional_information}}<br>
 </div>
 <div>
   <h3>Товары в заказе</h3>
 <table class="table table-bordered border-primary">
 <tr>
   {% if user.is_staff %}
   <td> pk book in cart</td>
   {% endif %}
 
   <td> Название </td>
   <td> Количечство </td>
   <td> Цена за единицу </td>
   <td> Цена за позицию </td>
   <td> Удалить </td>
 </tr>
 {% for book in object.cart.cart.all %}
 <tr>
   {% if user.is_staff %}
   <td>{{book.pk}}</td>
   {% endif %}
   <td> {{book}} </td>
   <td> {{book.quantity}} </td>
   <td> {{book.price}} </td>
   <td> {{book.price_per_position}} </td>
   <td> <a href= "{% url 'order:delete-position' pk=book.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить</a> </td>
 </tr>
 {% endfor %}
 </table>
 <p>Общая сумма заказа :{{object.cart.total_price}} </p>
    <h1>Редактровать данные заказа</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form |crispy}}
        <input type="submit" class="btn btn-success" value="Ok">
        </form>
{% endblock body %}

src/order/templates/order/status_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Изменить статус заказа
{% endblock title %}

{% block body %}
<h1>Вы действительно хотите отменить заказ?</h1>
<br><br><br><br>
<p>*для отмены заказа выберите 'Отменен'</p>
<p>
  <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form |crispy}}
  <input type="submit" class="btn btn-success" value="Ok">
  </form>
</p>

{% endblock body %}

src/order/templates/order/success_order.html
{% extends 'base.html' %}


{% block title %}
Заказ успешно оформлен
{% endblock title %}


{% block body %}

    <h1>Заказ {{ order }} успешно оформлен. Благодорим за покупку!</h1>
    <h2><a href= "{% url 'homepage:home' %}" class="btn btn-success">Вернуться на главную страницу</a></h2>

{% endblock body %}

src/order/templates/order/user_list_order.html
{% extends 'base.html' %}


{% block title %}
Мои Заказы
{% endblock title %}

{% block body %}


    <h1>Мои Заказы</h1>
    <table class="table table-bordered border-primary">
      <tr>
        <td>Изменить данные заказа</td>
        <td> Детали корзины </td>
        <td> Статус </td>
        <td> дата создания </td>
        <td> Дата редактирования </td>
      </tr>
    {% for obj in object_list %}
        {% if obj.order %}
         <tr>
           <td><a href= "{% url 'order:update-order' pk=obj.order.pk %}">Данные заказа №{{obj.order.pk}}  </a> </td>  
           <td><a href= "{% url 'order:detail-order' pk=obj.order.pk %}">Корзина №{{obj.pk}} </a></td> 
           <td> {{obj.order.status}}</td>
           <td>{{obj.order.created_date}} </td>
           <td>{{obj.order.updated_date}}</td>
        
    
        

        {% comment %} <td><a href= "{% url 'order:update-order' pk=obj.order.pk %}"> {{obj.pk}} </a> </td>  
        <td><a href= "{% url 'order:detail-order' pk=obj.order.pk %}">{{obj.cart}} </a></td> 
        <td><a href= "{% url 'order:staff-update-order' pk=obj.order.pk %}" class="btn btn-success"> {{obj.status}} </a></td>
        <td>{{obj.created_date}} </td>
        <td>{{obj.updated_date}}</td>  {% endcomment %}
        {% comment %} <td><a href= ""> {{obj.pk}} </a> </td>  
        <td><a href= "">{{obj.cart}} </a></td>
        <td><a href= "">{{obj.user}} </a></td>
        <td><a href= "">{{obj.order}} </a></td> {% endcomment %}
        {% comment %} <td><a href= "">{{obj.order.pk}} </a></td>
        <td><a href= "">{{obj.pk}} </a></td>
        <td><a href= "">{{obj.order.status}} </a></td>
        <td>{{obj.order.created_date}} </td>
        <td>{{obj.order.updated_date}}</td> {% endcomment %}
        {% endif %}
    {% endfor %}
    </table>        
    {% endblock body %}