src/book/urls.py
from django.urls import path
from . import views as b_views
app_name = 'book'
urlpatterns = [
    path('add-book/', b_views.AddBook.as_view(), name='add-book'),
    path('book/<int:pk>', b_views.DetailBook.as_view(), name='detail-book'),
    path('update-book/<int:pk>', b_views.UpdateBook.as_view(), name='update-book'),
    path('delete-book/<int:pk>', b_views.DeleteBook.as_view(), name='delete-book'),
    path('list-book/', b_views.ListBook.as_view(), name='list-book'),
    path('import-list-book/', b_views.book_list_import, name='import-list-book'),
    path('export-list-book/', b_views.book_list_export, name='export-list-book')

]

src/comments/urls.py
from django.urls import path
from . import views 
app_name = 'comments'
urlpatterns = [
    path('delete-comment-book/<int:pk>', views.DeleteCommentBook.as_view(), name='delete-comment-book'),
    path('delete-comment-order/<int:pk>', views.DeleteCommentOrder.as_view(), name='delete-comment-order')
]

src/guide/urls.py
from django.urls import path
from . import views as g_views
app_name = 'guide'

urlpatterns = [
    path('add-author/', g_views.AddAuthor.as_view(), name='add-author'),
    path('author/<int:pk>', g_views.DetailAuthor.as_view(), name='detail-author'),
    path('update-author/<int:pk>', g_views.UpdateAuthor.as_view(), name='update-author'),
    path('delete-author/<int:pk>', g_views.DeleteAuthor.as_view(), name='delete-author'),
    path('list-author/', g_views.ListAuthor.as_view(), name='list-author'),

    path('add-genre/', g_views.AddGenre.as_view(), name='add-genre'),
    path('genre/<int:pk>', g_views.DetailGenre.as_view(), name='detail-genre'),
    path('update-genre/<int:pk>', g_views.UpdateGenre.as_view(), name='update-genre'),
    path('delete-genre/<int:pk>', g_views.DeleteGenre.as_view(), name='delete-genre'),
    path('list-genre/', g_views.ListGenre.as_view(), name='list-genre'),

    path('add-series/', g_views.AddSeries.as_view(), name='add-series'),
    path('series/<int:pk>', g_views.DetailSeries.as_view(), name='detail-series'),
    path('update-series/<int:pk>', g_views.UpdateSeries.as_view(), name='update-series'),
    path('delete-series/<int:pk>', g_views.DeleteSeries.as_view(), name='delete-series'),
    path('list-series/', g_views.ListSeries.as_view(), name='list-series'),

    path('add-publishing/', g_views.AddPublishing.as_view(), name='add-publishing'),
    path('publishing/<int:pk>', g_views.DetailPublishing.as_view(), name='detail-publishing'),
    path('update-publishing/<int:pk>', g_views.UpdatePublishing.as_view(), name='update-publishing'),
    path('delete-publishing/<int:pk>', g_views.DeletePublishing.as_view(), name='delete-publishing'),
    path('list-publishing/', g_views.ListPublishing.as_view(), name='list-publishing')
]

src/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path("cart/", views.cart_view, name='cart'),
    path("delete-position/<int:pk>/", views.DeletePosition.as_view(), name='delete-position'),
    path("make-an-order/", views.MakeAnOrder.as_view(), name='make-an-order'),
    path("success/", views.SuccessView.as_view(), name='success'),
    path("list-order/", views.ListOrder.as_view(), name='list-order'),

    path('detail-order/<int:pk>', views.DetailOrder.as_view(), name='detail-order'),
    path('update-order/<int:pk>', views.UpdateOrder.as_view(), name='update-order'),
    path('delete-order/<int:pk>', views.DeleteOrder.as_view(), name='delete-order'),
    path('staff-update-order/<int:pk>', views.StaffUpdateOrder.as_view(), name='staff-update-order'),
    path("user-list-order/", views.UserListOrder.as_view(), name='user-list-order'),
    path("status-order/<int:pk>", views.UpdateStatusOrder.as_view(), name='status-order')

]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from adminpannel import views as ap_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("s-admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name = 'adminpannel/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("ref/", include('guide.urls', namespace='guide')),
    path("book/", include('book.urls', namespace='book')),
    path("", include('homepage.urls', namespace='homepage')),
    path("adminportal/", include('adminpannel.urls', namespace='adminportal')),
    path("order/", include('order.urls', namespace='order')),
    path("", include('custom_user.urls', namespace='custom_user')),
    path("comments", include('comments.urls', namespace='comments')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/book/models.py
from django.db import models
from django.urls import reverse_lazy


class Book(models.Model):
    """модель книги"""
    ZERO = '0'
    ONE = '1'
    TWO = '2'
    THREE = '3'
    FOUR = '4'
    FIVE = '5'
    SIX = '6'
    SEVEN = '7'
    EIGHT = '8'
    NINE = '9'
    TEN = '10'

    CHOISE_GROUP = {
        (ZERO, '0'),
        (ONE, '1'),
        (TWO, '2'),
        (THREE, '3'),
        (FOUR, '4'),
        (FIVE, '5'),
        (SIX, '6'),
        (SEVEN, '7'),
        (EIGHT, '8'),
        (NINE, '9'),
        (TEN, '10')
    }

    cover = models.ImageField(
        verbose_name='Обложка книги',
        upload_to='uploads/%Y/%m/%d'

    )

    name = models.CharField(
        verbose_name='Название',
        max_length=40
    )

    author_book = models.ManyToManyField(
        'guide.Author',
        verbose_name='Автор',
        related_name='authorbook',
    )

    series_book = models.ForeignKey(
        'guide.Series',
        verbose_name='Серия',
        on_delete=models.PROTECT,
        related_name='seriesbook'
    )

    genre_book = models.ForeignKey(
        'guide.Genre',
        verbose_name='Жанр',
        on_delete=models.PROTECT,
        related_name='genrebook'
    )
    publishing_book = models.ForeignKey(
        'guide.Publishing',
        verbose_name='Издательство',
        on_delete=models.PROTECT,
        related_name='publishingbook'
    )

    price = models.DecimalField(
        verbose_name='Цена',
        max_digits=5,
        decimal_places=2
    )
    last_change = models.DateField(
        verbose_name='Дата последнего изменение карточки',
        auto_now=True
    )
    add_to_catalog = models.DateField(
        verbose_name='Дата добавления в каталог',
        auto_now_add=True
    )

    quantity_available = models.PositiveSmallIntegerField(
        verbose_name='Количество в наличии'
    )

    weight = models.PositiveSmallIntegerField(
        verbose_name='Вес(гр.)',
        blank=True,
        null=True
    )
    quantity_of_pages = models.PositiveSmallIntegerField(
        verbose_name='Количество страниц',
        blank=True,
        null=True
    )

    binding = models.TextField(
        verbose_name='Переплет',
        max_length=100,
        blank=True,
        null=True
    )

    book_format = models.TextField(
        verbose_name='Формат',
        max_length=100,
        blank=True,
        null=True
    )

    year_of_publication = models.DecimalField(
        verbose_name='Год издания',
        max_digits=4,
        decimal_places=0,
        blank=True,
        null=True
    )

    isbn = models.TextField(
        verbose_name='ISBN',
        max_length=100,
        blank=True,
        null=True
    )

    age_restrictions = models.TextField(
        verbose_name='Возрастные ограничения',
        max_length=10,
        blank=True,
        null=True
    )

    rating = models.CharField(
        verbose_name='Рейтинг',
        max_length=50,
        choices=CHOISE_GROUP,
        default=ZERO

    )

    availability = models.BooleanField(
        verbose_name='Доступен для заказа'
    )

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse_lazy('book:detail-book', kwargs={'pk': self.pk})

src/book/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class BookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'

src/book/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from comments import models as c_models
from comments import forms as c_forms
from django.views.generic.edit import FormMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
from tablib import Dataset

from .resources import BookResource

from . import models, forms


# кинги:

class AddBook(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = models.Book
    form_class = forms.BookForm
    permission_required = 'book.add_book'
    login_url = reverse_lazy('login')
    template_name = 'book/edit_book.html'
    success_url = reverse_lazy('book:list-book')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Добавить книгу'
        return context


class DetailBook(FormMixin, generic.DetailView):
    model = models.Book
    template_name = 'book/detail_book.html'
    form_class = c_forms.CommentToBookForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        return self.form_valid(form)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.book = self.get_object()
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('book:detail-book', kwargs={'pk': self.get_object().pk})


class UpdateBook(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Book
    form_class = forms.BookForm
    permission_required = 'book.add_book'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('book:list-book')
    template_name = 'book/edit_book.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Редактировать данные о книге'
        return context


class DeleteBook(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Book
    permission_required = 'book.delete_book'
    login_url = reverse_lazy('login')
    template_name = 'book/delete_book.html'
    success_url = reverse_lazy('book:list-book')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Удалить книгу'
        context['alarm_message'] = 'Вы точно хотите удалить данную книгу?'
        return context


class ListBook(generic.ListView):
    model = models.Book
    template_name = 'book/list_book.html'


# импорт/экспорт списков книг

def book_list_export(request):
    if request.user.is_authenticated == request.user.is_staff:
        if request.method == 'POST':
            file_format = request.POST['file-format']
            book_resource = BookResource()
            dataset = book_resource.export()
            if file_format == 'CSV':
                response = HttpResponse(dataset.csv, content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename="exported_data.csv"'
                return response
            elif file_format == 'JSON':
                response = HttpResponse(dataset.json, content_type='application/json')
                response['Content-Disposition'] = 'attachment; filename="exported_data.json"'
                return response
            elif file_format == 'XLS (Excel)':
                response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
                response['Content-Disposition'] = 'attachment; filename="exported_data.xls"'
                return response

        return render(request, 'book/export_book.html')
    else:
        raise PermissionDenied()


def book_list_import(request):
    if request.user.is_authenticated == request.user.is_staff:
        if request.method == 'POST':
            file_format = request.POST['file-format']
            book_resource = BookResource()
            dataset = Dataset()
            new_book = request.FILES['importData']

            if file_format == 'CSV':
                imported_data = dataset.load(new_book.read().decode('utf-8'), format='csv')
                result = book_resource.import_data(dataset, dry_run=True)
            elif file_format == 'JSON':
                imported_data = dataset.load(new_book.read().decode('utf-8'), format='json')
                result = book_resource.import_data(dataset, dry_run=True)

            if not result.has_errors():
                book_resource.import_data(dataset, dry_run=False)

        return render(request, 'book/import_book.html')
    else:
        raise PermissionDenied()

src/book/templates/book/delete_book.html
{% extends 'base.html' %}


{% block title %}
{{operation}}
{% endblock title %}

{% block body %}
    <h1>{{operation}}</h1>
    <h2>{{alarm_message}}</h2>
    {{object.pk}}<br>
    {{object.name}}<br>

   {% if object.author_book.all.count != 1 %}
   Авторы:<br>
   {% else %}
   Автор:<br>
   {% endif %}
   {% for author in object.author_book.all %}
   <ul>
    <li>
   {{author}}<br>
    </li>
   </ul>
   {% endfor %}

    {{object.genre_book}}<br>
    {{object.price}}<br>            
    <form method = 'post'>
        {%csrf_token%}           
        <button type="submit" class="btn btn-danger">ДА</button>
    </form>
{% endblock body %}

src/book/templates/book/detail_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
Информация о книге
{% endblock title %}

{% block body %}
{% csrf_token %}
    <h1>Информация о книге</h1>
   
   <img src="{{ book.cover.url }}" >
   <div>
   ID книги: {{object.pk}}<br>
   Название: {{object.name}}<br>
   {% if object.author_book.all.count != 1 %}
   Авторы:<br>
   {% else %}
   Автор:<br>
   {% endif %}
   {% for author in object.author_book.all %}
   <ul>
    <li>
   <a href="{% url 'guide:detail-author' pk=author.pk %}"> {{author}} </a><br>
    </li>
   </ul>
   {% endfor %}
   <a href="{% url 'guide:detail-genre' pk=object.genre_book.pk %}">  Жанр: {{object.genre_book}}</a><br>
   <a href="{% url 'guide:detail-series' pk=object.series_book.pk %}"> Серия: {{object.series_book}}</a> <br>
   <a href="{% url 'guide:detail-publishing' pk=object.publishing_book.pk %}"> Издательство: {{object.publishing_book}}</a> <br>
   Дата добавления: {{object.add_to_catalog}}<br>
   Количество в наличии: {{object.quantity_available}}<br>
   Вес книги: {{object.weight}} гр.<br>
   Количество страниц: {{object.quantity_of_pages}}<br>
   Переплет {{object.binding}}<br>
   Формат: {{object.book_format}}<br>
   Год издательства: {{object.year_of_publication}}<br>
   ISBN: {{object.isbn}}<br>
   Возрастные ограниччения: {{object.age_restrictions}}<br>
   Рейтинг: {{object.rating}}<br>
   Цена: {{object.price}} BYN<br>
</div>
<br>
<div>
    <form action="{% url 'order:cart' %}" method="post">
        {% csrf_token %}
         <button type="submit" class="btn btn-success">Добавить в корзину</button>  Количество:<input type="number" name="quantity" value="1" min="1"><br>
        <input type="hidden" name="book_pk" value="{{object.pk}}">
    </form>
</div>
<br>
<div>
    {% if object.book_comment.all.count == 0  %}
    <p>Комментариев нет<br>
     Оставьте комментарий первым!
    </p>
    {% else %}
    <p>Комментарии к книге({{object.book_comment.all.count}}):</p>
    <ul>
    {% for comment in object.book_comment.all %}
    <li>
        {% if user.is_staff %}
        pk комментария: {{comment.pk}}<br>
        {% endif %}
        автор:{{comment.author}} <br>
        {{comment.create_date}} <br>
        сообщение:{{comment.message}} <br>
        <br>
        {% if user.is_authenticated %}
        
            {% if user.is_authenticated != user.is_staff %}
                {% if user == comment.author %}
                    <a href= "{% url 'comments:delete-comment-book' pk=comment.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить комментарий</a><br><br>
                {% else %}
        {% comment %} <a href= "{% url 'comments:delete-comment-book' pk=comment.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить комментарий</a><br><br> {% endcomment %}
                {% endif %}
            {% else %}
            <a href= "{% url 'comments:delete-comment-book' pk=comment.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить комментарий</a><br><br>
            {% endif %}
            
        {% endif %}
        
         
    </li>
    {% endfor %}
    </ul>
    {% endif %}
    <p>
        {% if user.is_authenticated %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form |crispy}}
        <input type="submit" class="btn btn-success" value="Ok">
        </form>
        {% else %}
        <p>Зарегистрируйтесь чтобы оставлять комментарии </p>
        {% endif %}
    </p>
</div>

{% endblock body %}

src/book/templates/book/edit_book.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
{{ operation }}
{% endblock title %}

{% block body %}
    <h1>{{operation}}</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form |crispy}}
        <input type="submit" class="btn btn-success" value="Ok">
        </form>
{% endblock body %}

src/book/templates/book/export_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Выгрузка списка книг
{% endblock title %}

{% block body %}
    <h1>Выгрузка списка книг</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <p>Выберете формат файла</p>
        <select name="file-format" class="form-control my-3"><option selected>Выберете формат</option><option>CSV</option><option>JSON</option><option>XLS (Excel)</option></select><br>
        <button class="btn btn-primary" type="submit">Выгрузить</button><br>
      </form>
{% endblock body %}

src/book/templates/book/import_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Загрузка списка книг
{% endblock title %}

{% block body %}
    <h1>Загрузка списка книг</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}<br />
        <input type="file" name="importData"></p>
    <p>Выберете формат файла</p>
    <p>    <select name="file-format" class="form-control my-3"><option selected>Выберете формат...</option><option>CSV</option><option>JSON</option></select><br />
        <button class="btn btn-primary" type="submit">Import</button><br />
      </form>
{% endblock body %}

src/book/templates/book/list_book.html
{% extends 'base.html' %}


{% block title %}
Список книг
{% endblock title %}

{% block body %}


    <h1>Список книг</h1>
    <table class="table table-bordered border-primary">
    <tr>
      <td>Название</td>
      <td>Автор</td>
      <td>Жанр</td>
      <td>Доступен к заказу</td>
      <td>Цена</td>
      <td>Добавить в корзину</td>
      <td>Количество</td>
      {% if user.is_staff %}
      
      <td>Дата поступления</td>
      <td>ID/Редакторвать</td>
      <td>Доступное количество</td>
      <td>Удалить</td>
      {% endif %}
    </tr>
    {% for obj in object_list %}
    <tr>

        <td><a href= "{% url 'book:detail-book' pk=obj.pk %}">{{obj.name}} </a></td>
        <td>
        {% for author in obj.author_book.all %}
         {{author}}<br> 
        {% endfor %}
      </td>
        <td> {{obj.genre_book}}</td>
        {% if obj.availability == True %}
        <td> Доступен</td>
        {% else %}
        <td>Недоступен</td>
        {% endif %}
        <td>{{obj.price}}руб.</td>

        {% if obj.availability == True %}
      <form action="{% url 'order:cart' %}" method="post">
        {% csrf_token %}
        <td> <button type="submit" class="btn btn-success">Добавить в корзину</button></td>
        <td>Количество:<input type="number" name="quantity" value="1" min="1"></td>
        <input type="hidden" name="book_pk" value="{{obj.pk}}">
    </form>
    {% else %}
    <td> <button type="submit" class="btn btn-secondary">Недоступен для заказа</button></td>
        <td><i class="bi bi-emoji-frown"></i></td>
  
    {% endif %}


        {% if user.is_staff %} 
        <td>{{obj.add_to_catalog}}</td>
        <td><a href= "{% url 'book:update-book' pk=obj.pk %}"> {{obj.pk}} </a> </td>
        <td> {{obj.quantity_available}}шт.</td>  
        <td><a href= "{% url 'book:delete-book' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>Удалить</a></td>
      {% endif %} 
      </tr> 
    {% endfor %}
    </table>        
    {% endblock body %}